// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChH1PlN35rFwSbEcjBuv9Ue4zM_lsvchU',
    appId: '1:864062421856:web:4b4bca4c3dd404c17b3c05',
    messagingSenderId: '864062421856',
    projectId: 'flutter-chat-app-b870f',
    authDomain: 'flutter-chat-app-b870f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b870f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdDm-MZTR53WvN5PQ1MBlGIAke8FSfTk',
    appId: '1:864062421856:android:3e1d97dfbcfecbdc7b3c05',
    messagingSenderId: '864062421856',
    projectId: 'flutter-chat-app-b870f',
    storageBucket: 'flutter-chat-app-b870f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLVE9YMNdz_o0v1e7cVDnLWiMuL7nK_o',
    appId: '1:864062421856:ios:c37b249243a303e47b3c05',
    messagingSenderId: '864062421856',
    projectId: 'flutter-chat-app-b870f',
    storageBucket: 'flutter-chat-app-b870f.appspot.com',
    iosBundleId: 'com.example.infinityEdgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChH1PlN35rFwSbEcjBuv9Ue4zM_lsvchU',
    appId: '1:864062421856:web:d9417ccf8a6a115d7b3c05',
    messagingSenderId: '864062421856',
    projectId: 'flutter-chat-app-b870f',
    authDomain: 'flutter-chat-app-b870f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b870f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLVE9YMNdz_o0v1e7cVDnLWiMuL7nK_o',
    appId: '1:864062421856:ios:c37b249243a303e47b3c05',
    messagingSenderId: '864062421856',
    projectId: 'flutter-chat-app-b870f',
    storageBucket: 'flutter-chat-app-b870f.appspot.com',
    iosBundleId: 'com.example.infinityEdgeApp',
  );

}